name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Устанавливаем Node.js 20-й версии
          cache: 'npm'
          run: make install
          run: make test
          run: make lint
          uses: hexlet-components/hello-from-hexlet-action@release  # Запускаем кастомный экшен

